spring:
  application:
    name: bean-validator-application
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /